# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.2

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/clion/bin/cmake/linux/x64/bin/cmake

# The command to remove a file.
RM = /opt/clion/bin/cmake/linux/x64/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/dariushg/ten

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/dariushg/ten

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/clion/bin/cmake/linux/x64/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/dariushg/ten/CMakeFiles /home/dariushg/ten//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/dariushg/ten/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ten

# Build rule for target.
ten: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ten
.PHONY : ten

# fast build rule for target.
ten/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ten.dir/build.make CMakeFiles/ten.dir/build
.PHONY : ten/fast

#=============================================================================
# Target rules for targets named ten_tests

# Build rule for target.
ten_tests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ten_tests
.PHONY : ten_tests

# fast build rule for target.
ten_tests/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ten_tests.dir/build.make CMakeFiles/ten_tests.dir/build
.PHONY : ten_tests/fast

src/builder/builder.o: src/builder/builder.cc.o
.PHONY : src/builder/builder.o

# target to build an object file
src/builder/builder.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ten.dir/build.make CMakeFiles/ten.dir/src/builder/builder.cc.o
.PHONY : src/builder/builder.cc.o

src/builder/builder.i: src/builder/builder.cc.i
.PHONY : src/builder/builder.i

# target to preprocess a source file
src/builder/builder.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ten.dir/build.make CMakeFiles/ten.dir/src/builder/builder.cc.i
.PHONY : src/builder/builder.cc.i

src/builder/builder.s: src/builder/builder.cc.s
.PHONY : src/builder/builder.s

# target to generate assembly for a file
src/builder/builder.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ten.dir/build.make CMakeFiles/ten.dir/src/builder/builder.cc.s
.PHONY : src/builder/builder.cc.s

src/codegen/c_backend.o: src/codegen/c_backend.cc.o
.PHONY : src/codegen/c_backend.o

# target to build an object file
src/codegen/c_backend.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ten.dir/build.make CMakeFiles/ten.dir/src/codegen/c_backend.cc.o
.PHONY : src/codegen/c_backend.cc.o

src/codegen/c_backend.i: src/codegen/c_backend.cc.i
.PHONY : src/codegen/c_backend.i

# target to preprocess a source file
src/codegen/c_backend.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ten.dir/build.make CMakeFiles/ten.dir/src/codegen/c_backend.cc.i
.PHONY : src/codegen/c_backend.cc.i

src/codegen/c_backend.s: src/codegen/c_backend.cc.s
.PHONY : src/codegen/c_backend.s

# target to generate assembly for a file
src/codegen/c_backend.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ten.dir/build.make CMakeFiles/ten.dir/src/codegen/c_backend.cc.s
.PHONY : src/codegen/c_backend.cc.s

src/codegen/lower.o: src/codegen/lower.cc.o
.PHONY : src/codegen/lower.o

# target to build an object file
src/codegen/lower.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ten.dir/build.make CMakeFiles/ten.dir/src/codegen/lower.cc.o
.PHONY : src/codegen/lower.cc.o

src/codegen/lower.i: src/codegen/lower.cc.i
.PHONY : src/codegen/lower.i

# target to preprocess a source file
src/codegen/lower.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ten.dir/build.make CMakeFiles/ten.dir/src/codegen/lower.cc.i
.PHONY : src/codegen/lower.cc.i

src/codegen/lower.s: src/codegen/lower.cc.s
.PHONY : src/codegen/lower.s

# target to generate assembly for a file
src/codegen/lower.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ten.dir/build.make CMakeFiles/ten.dir/src/codegen/lower.cc.s
.PHONY : src/codegen/lower.cc.s

src/ir/lower.o: src/ir/lower.cc.o
.PHONY : src/ir/lower.o

# target to build an object file
src/ir/lower.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ten.dir/build.make CMakeFiles/ten.dir/src/ir/lower.cc.o
.PHONY : src/ir/lower.cc.o

src/ir/lower.i: src/ir/lower.cc.i
.PHONY : src/ir/lower.i

# target to preprocess a source file
src/ir/lower.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ten.dir/build.make CMakeFiles/ten.dir/src/ir/lower.cc.i
.PHONY : src/ir/lower.cc.i

src/ir/lower.s: src/ir/lower.cc.s
.PHONY : src/ir/lower.s

# target to generate assembly for a file
src/ir/lower.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ten.dir/build.make CMakeFiles/ten.dir/src/ir/lower.cc.s
.PHONY : src/ir/lower.cc.s

src/runtime/runtime.o: src/runtime/runtime.cc.o
.PHONY : src/runtime/runtime.o

# target to build an object file
src/runtime/runtime.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ten.dir/build.make CMakeFiles/ten.dir/src/runtime/runtime.cc.o
.PHONY : src/runtime/runtime.cc.o

src/runtime/runtime.i: src/runtime/runtime.cc.i
.PHONY : src/runtime/runtime.i

# target to preprocess a source file
src/runtime/runtime.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ten.dir/build.make CMakeFiles/ten.dir/src/runtime/runtime.cc.i
.PHONY : src/runtime/runtime.cc.i

src/runtime/runtime.s: src/runtime/runtime.cc.s
.PHONY : src/runtime/runtime.s

# target to generate assembly for a file
src/runtime/runtime.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ten.dir/build.make CMakeFiles/ten.dir/src/runtime/runtime.cc.s
.PHONY : src/runtime/runtime.cc.s

src/scheduler/tile_index.o: src/scheduler/tile_index.cc.o
.PHONY : src/scheduler/tile_index.o

# target to build an object file
src/scheduler/tile_index.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ten.dir/build.make CMakeFiles/ten.dir/src/scheduler/tile_index.cc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ten_tests.dir/build.make CMakeFiles/ten_tests.dir/src/scheduler/tile_index.cc.o
.PHONY : src/scheduler/tile_index.cc.o

src/scheduler/tile_index.i: src/scheduler/tile_index.cc.i
.PHONY : src/scheduler/tile_index.i

# target to preprocess a source file
src/scheduler/tile_index.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ten.dir/build.make CMakeFiles/ten.dir/src/scheduler/tile_index.cc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ten_tests.dir/build.make CMakeFiles/ten_tests.dir/src/scheduler/tile_index.cc.i
.PHONY : src/scheduler/tile_index.cc.i

src/scheduler/tile_index.s: src/scheduler/tile_index.cc.s
.PHONY : src/scheduler/tile_index.s

# target to generate assembly for a file
src/scheduler/tile_index.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ten.dir/build.make CMakeFiles/ten.dir/src/scheduler/tile_index.cc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ten_tests.dir/build.make CMakeFiles/ten_tests.dir/src/scheduler/tile_index.cc.s
.PHONY : src/scheduler/tile_index.cc.s

tests/test.o: tests/test.cc.o
.PHONY : tests/test.o

# target to build an object file
tests/test.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ten_tests.dir/build.make CMakeFiles/ten_tests.dir/tests/test.cc.o
.PHONY : tests/test.cc.o

tests/test.i: tests/test.cc.i
.PHONY : tests/test.i

# target to preprocess a source file
tests/test.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ten_tests.dir/build.make CMakeFiles/ten_tests.dir/tests/test.cc.i
.PHONY : tests/test.cc.i

tests/test.s: tests/test.cc.s
.PHONY : tests/test.s

# target to generate assembly for a file
tests/test.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ten_tests.dir/build.make CMakeFiles/ten_tests.dir/tests/test.cc.s
.PHONY : tests/test.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... ten"
	@echo "... ten_tests"
	@echo "... src/builder/builder.o"
	@echo "... src/builder/builder.i"
	@echo "... src/builder/builder.s"
	@echo "... src/codegen/c_backend.o"
	@echo "... src/codegen/c_backend.i"
	@echo "... src/codegen/c_backend.s"
	@echo "... src/codegen/lower.o"
	@echo "... src/codegen/lower.i"
	@echo "... src/codegen/lower.s"
	@echo "... src/ir/lower.o"
	@echo "... src/ir/lower.i"
	@echo "... src/ir/lower.s"
	@echo "... src/runtime/runtime.o"
	@echo "... src/runtime/runtime.i"
	@echo "... src/runtime/runtime.s"
	@echo "... src/scheduler/tile_index.o"
	@echo "... src/scheduler/tile_index.i"
	@echo "... src/scheduler/tile_index.s"
	@echo "... tests/test.o"
	@echo "... tests/test.i"
	@echo "... tests/test.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

